"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-0gzzd&b5#)f2**v7dn@^-w&1=6%l1y=iynu3iks+rj)yp!85wu"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "store",  # dev_1
    "django.contrib.humanize",  # dev_5
    "accounts",  # dev_9
    "cart",  # dev_15
    "orders",  # dev_24
    "payment",  # dev_26
    "rest_framework",  # dev_28
    "api",  # dev_28
    "corsheaders",  # dev_36
    "djoser",  # dev_38
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # dev_36
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
# dev_36
# 정확히 허용할 도메인만
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # 프론트 도메인
]
CORS_ORIGIN_ALLOW_ALL = True  # 어떠한 출처든 상관없이 정보를 공유
# dev_38
CORS_ALLOW_CREDENTIALS = True
# 쿠키 관련
SESSION_COOKIE_SECURE = False  # 로컬에서는 반드시 False (HTTPS에서만 전송 X)
CSRF_COOKIE_SECURE = False  # 로컬에서는 False
SESSION_COOKIE_SAMESITE = "Lax"  # 또는 "None" (같은 도메인만 허용 시 Lax)
CSRF_COOKIE_SAMESITE = "Lax"


ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # dev_1
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "cart.context_processors.cart",  # dev_17 cart(request)가 모든 템플릿에서 사용 가능해짐.
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# dev_11
AUTH_PASSWORD_VALIDATORS = [
    # {
    #     "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    # },
    # {
    #     "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    # },
    # {
    #     "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    # },
    # {
    #     "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "ko-kr"  # dev_1

TIME_ZONE = "Asia/Seoul"  # dev_1


USE_I18N = True

# dev_5
# Timezone의 사용여부를 정한다.
# False면 모든 datetime들을 표시하고 True면 template과 form에만 적용된다.
# 즉 DB에 저장되는 정보도 한국 시간대로 사용하려면 이 부분을 False로 지정해주어야 한다.
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# dev_2
# 스태틱(static) 디렉터리
# URL 상의 스택틱 폴더를 ,로컬(내컴퓨터)의 파일 폴더와 매칭 시키는 부분
# http://127.0.0.1:8000/static/a.jpg
STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 미디어 파일 경로 설정
import os

# dev_2
# http://127.0.0.1:8000/media/파일경로
MEDIA_URL = "media/"  # ex) /media/photo1.png
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# dev_9
# 다시 한번 migrate 시켜줘야함
AUTH_USER_MODEL = "accounts.User"

# dev_15
CART_SESSION_ID = "cart"

# dev_38
# Simple JWT 패키지를 써서 JWT(JSON Web Token) 기반 인증을 사용하겠다고 설정
# 세션 쿠키 기반 인증보다 더 RESTful (stateless)
# 모바일/프론트엔드 앱과 연동이 편함 (React, Vue 등)
# 백엔드 서버에 로그인 상태 유지할 필요 없음

# https://chatgpt.com/c/67ef7abf-2fbc-8007-be16-ed6e3f036f00
# ❗ 특징:
# 서버는 아무것도 기억하지 않음 → Stateless
# 인증은 토큰 안에 담긴 정보로 바로 판단함
# 확장성 좋고, 여러 서비스(API 서버, 프론트 서버)에서도 공유하기 쉬움

# 🔐 주요 엔드포인트 예시
# 경로	설명
# POST /auth/jwt/create/	로그인 (토큰 발급)
# POST /auth/jwt/refresh/	액세스 토큰 갱신
# POST /auth/jwt/verify/	토큰 유효성 확인
# POST /auth/users/	회원가입
# GET /auth/users/me/	현재 로그인된 사용자 조회

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",  # 추가
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

#    'AUTH_HEADER_TYPES': ('JWT',),
#    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
#    'REFRESH_TOKEN_LIFETIME': timedelta(days=2),
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),  # timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}
# http://127.0.0.1:8000/api/auth/users/me/
DJOSER = {
    "USER_ID_FIELD": "id",
    "LOGIN_FIELD": "username",  # 또는 email
    "SERIALIZERS": {
        "user_create": "accounts.serializers.UserCreateSerializer",
        "user": "accounts.serializers.UserSerializer",
        "current_user": "accounts.serializers.UserSerializer",
    },
    "CREATE_SESSION_ON_LOGIN": True,  # 로그인하면 세션도 생성됨
}
